# yaml-language-server: $schema=../../config.schema.json
log:
  log_level: {type: Debug}
time_analysis:
  exporter: 
    type: TraceEventExporter
  output_path: "time_performance"
  keep_last: true
results: {} #default results
max_time: 60.
random_seed: 85646513.6849618
robots:
  - name: "robot1"
    navigator: 
      type: TrajectoryFollower
      trajectory_path: "paths/path1.yaml"
      target_speed: 0.5
      forward_distance: 0.2
    controller:
      type: PID
      proportional_gains: [1.0, 6.0]
    sensor_manager:
      sensors:
        - name: "RobotSensor"
          send_to: ["Central Unit"]
          config:
            type: RobotSensor
            period: 0.1
            detection_distance: 100.0
        - name: "LandmarkSensor"
          config: 
            type: OrientedLandmarkSensor
            map_path: "maps/landmarks_square.yaml"
            detection_distance: 10.0
            faults:
              - type: AdditiveRobotCentered # Gaussian White Noise
                variable_order: [x, y, orientation]
                distributions:
                  - type: Normal
                    mean: [0, 0, 0]
                    covariance: [0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01]
                    
  - name: "robot2"
    navigator:
      type: TrajectoryFollower
      trajectory_path: "paths/path1.yaml"
      target_speed: 0.3
      forward_distance: 0.2
    physics: 
      type: Internal
      model:
        type: Holonomic
    controller: 
      type: PID
      proportional_gains: [1.0, 3.0]
    sensor_manager:
      sensors:
        - name: "RobotSensor"
          send_to: ["Central Unit"]
          config: 
            type: RobotSensor
            period: 0.1
            detection_distance: 100.0
computation_units:
  - name: "Central Unit"
    network:
      reception_delay: 0.
    state_estimators:
      - name: "central_perfect"
        config: 
          type: Perfect
          targets: ["robot1", "robot2"]
          prediction_period: 0.1