[package]
name = "turtlebot_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "^0.32.3", features = ["serde"] }
serde_derive = "^1.0"
serde = "^1.0"
libm = "^0.2.7"

[dependencies.confy]
version = "^0.5"
features = ["yaml_conf"]
default-features = false