[package]
name = "turtlebot_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "^0.32.3", features = ["serde"] }
serde_derive = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
libm = "^0.2.7"
plotters = "^0.3.2"
plotters-canvas = "^0.3.0"
csv = "1.3.0"
serde_json = "1.0.107"

[dependencies.confy]
version = "^0.5"
features = ["yaml_conf"]
default-features = false
