[workspace]
members = ["example"]

[package]
name = "turtlebot_simulator"
version = "0.2.0"
edition = "2021"

crate-type = ["cdylib"]
doctest = false

[features]
time-analysis = [] # Enable time analysis features. May slow down the simulation (shared memory).


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turtlebot_simulator_macros = { path = "macros" }
nalgebra = { version = "^0.32", features = ["serde"] }
serde_derive = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
libm = "^0.2.7"
# plotters = "^0.3.2"
# plotters-canvas = "^0.3.0"
# csv = "1.3.0"
serde_json = "1.0.107"
lazy_static = "1.5.0"

egui = { git = "https://github.com/emilk/egui", tag = "0.27.2" }
eframe = { git = "https://github.com/emilk/egui", tag = "0.27.2" , default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
log = "^0.4.22"
rand = "0.8.5"
rand_chacha = "0.3.1"
statrs = "0.17.1"


[dependencies.pyo3]
version = "^0.22"

[dependencies.confy]
version = "^0.5"
features = ["yaml_conf"]
default-features = false

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"


[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2


[patch.crates-io]
