[workspace]
members = ["example"]

[package]
name = "turtlebot_simulator"
version = "0.1.0"
edition = "2021"

crate-type = ["cdylib"]

doctest = false



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "^0.32", features = ["serde"] }
serde_derive = "^1.0"
serde = { version = "^1.0", features = ["derive"] }
libm = "^0.2.7"
# plotters = "^0.3.2"
# plotters-canvas = "^0.3.0"
# csv = "1.3.0"
serde_json = "1.0.107"

egui = { git = "https://github.com/emilk/egui", tag = "0.27.2" }
eframe = { git = "https://github.com/emilk/egui", tag = "0.27.2" , default-features = false, features = [
    "accesskit",     # Make egui comptaible with screen readers. NOTE: adds a lot of dependencies.
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
log = "^0.4.22"

[dependencies.pyo3]
version = "^0.22"
[features]
extension-module = ["pyo3/extension-module"]

[dependencies.confy]
version = "^0.5"
features = ["yaml_conf"]
default-features = false

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"


[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2


[patch.crates-io]
