[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "simba"
requires-python = ">=3.7"
version = "0.4.2-dev"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]


[tool.maturin]
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
features = ["pyo3/extension-module", "time-analysis"]