newline_style = "Unix"
# Unstable:
# format_code_in_doc_comments = true
# imports_granularity = "Crate"
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
# group_imports = "StdExternalCrate"