[package]
name = "simba_cmd"
version = "1.1.0"
edition = "2021"

[dependencies]
simba = { path = "..", features = ["gui", "time-analysis"], version = "*"}
clap = { version = "4.5.48", features = ["derive"] }