[package]
name = "my_rust_plugin"
version = "0.1.0"
edition = "2021"

crate-type = ["cdylib"]

[dependencies]
simba = { path = "../..", features = ["gui"], version = "*"}
pyo3 ={ version = "^0.22", features = ["extension-module"]}
serde_json = "1.0.145"
serde = "1.0.228"
