robots:
  - name: "robot1"
    navigator:
      TrajectoryFollower:
        trajectory_path: "paths/path1.yaml"
        target_speed: 0.5
        forward_distance: 0.2
    controller:
      PID:
        kp_v: 1.0
        kp_theta: 6.0
    state_estimator:
      External:
        period: 0.1
  - name: "robot2"
    navigator:
      TrajectoryFollower:
        trajectory_path: "paths/path1.yaml"
        target_speed: 0.5
        forward_distance: 0.2
    controller:
      PID:
        kp_v: 1.0
        kp_theta: 6.0
    state_estimator:
      External:
        period: 0.2