[package]
name = "simba-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true


[dependencies]
syn = "^2.0.90"
quote = "^1.0.37"
proc-macro2 = "^1.0.92"
