log:
  log_level:
    Info
results: 
  result_path: "./result.json"
  show_figures: true # Disabled for automatic testing
  analyse_script: "../python_scripts/analyse_results.py"
  figures_path: "./figures"
  save_mode: !AtTheEnd #default: AtTheEnd.  Possibilities: !Continuous, !Periodic [period], !Batch [time_step_batch_size]
time_analysis:
  exporter: TraceEventExporter
  output_path: "time_performance"
  keep_last: true
max_time: 60.
robots:
  - name: "robot1"
    navigator: !TrajectoryFollower
      <<: &Navigator
        trajectory_path: "paths/path1.yaml"
        target_speed: 0.5
        forward_distance: 0.2
    controller: !PID
      <<: &PID # Merge YAML feature: https://yaml.org/type/merge.html
        kp_v: 1.0
        kp_theta: 3.0
    sensor_manager:
      sensors:
        - <<: &RobotSensor
            name: "RobotSensor"
            send_to: ["Central Unit"]
            config: !RobotSensor
              period: 0.1
              detection_distance: 100.0
        - name: "LandmarkSensor"
          config: !OrientedLandmarkSensor
            map_path: "maps/landmarks_square.yaml"
            detection_distance: 10.0
            faults:
              - !AdditiveRobotCentered # Gaussian White Noise
                variable_order: [x, y, orientation]
                distributions:
                  - !Normal
                    unique_seed: 95698.956258563245 #Merge dangerous with seeds: Same seed on all merges
                    mean: [0, 0, 0]
                    covariance: [0.01, 0, 0, 0, 0.01, 0, 0, 0, 0.01]
  - name: "robot2"
    navigator: !TrajectoryFollower
      <<: *Navigator
      target_speed: 0.3
    controller: !PID
      <<: *PID
    sensor_manager:
      sensors:
        - <<: *RobotSensor
computation_units:
  - name: "Central Unit"
    state_estimators:
      - name: "central_perfect"
        config: !Perfect
          targets: ["robot1", "robot2"]
          prediction_period: 0.1