# yaml-language-server: $schema=../config.schema.json
version: 1.4.5
log:
  included_nodes: []
  excluded_nodes: []
  log_level:
    type: Info
results: {}
max_time: 20.0
time_analysis:
  exporter:
    type: TraceEventExporter
  keep_last: true
  output_path: time_performance
  analysis_unit: s
random_seed: null
robots:
- name: robot1
  navigator: 
    type: TrajectoryFollower
    trajectory_path: paths/path1.yaml
    forward_distance: 0.2
    target_speed: 0.5
    stop_distance: 0.2
    stop_ramp_coefficient: 0.5
  controller: 
    type: PID
  physics: 
    type: Internal
    model: 
      type: Unicycle
      wheel_distance: 0.25
    initial_state:
      pose:
      - 0.0
      - 0.0
      - 0.0
      velocity: [0.0, 0.0]
    faults:
    - type: AdditiveRobotCentered
      distributions:
      - type: Normal
        mean:
        - 0.0
        - 0.0
        covariance:
        - 0.1
        - 0.0
        - 0.0
        - 0.1
      variable_order:
      - x
      - y
  state_estimator:
    type: Perfect
    prediction_period: 0.1
    targets:
    - self
    map_path: null
  sensor_manager:
    sensors:
    - name: RobotSensor
      send_to:
      - Central Unit
      config:
        type: RobotSensor
        detection_distance: 100.0
        period: 0.1
        faults: []
    - name: LandmarkSensor
      config: 
        type: OrientedLandmarkSensor
        detection_distance: 100.0
        map_path: maps/landmarks_obstruction.yaml
        period: 0.1
        faults:
        - type: AdditiveRobotCentered
          apparition:
            probability:
            - 1.0
          distributions:
          - type: Normal
            mean:
            - 0.0
            - 0.0
            - 0.0
            - 0.0
            covariance:
            - 0.01
            - 0.0
            - 0.0
            - 0.0
            - 0.0
            - 0.01
            - 0.0
            - 0.0
            - 0.0
            - 0.0
            - 0.01
            - 0.0
            - 0.0
            - 0.0
            - 0.0
            - 0.3
          variable_order:
          - x
          - y
          - orientation
          - width
  network:
    range: 0.0
    reception_delay: 0.0
  state_estimator_bench: []
- name: robot2
  navigator: 
    type: TrajectoryFollower
    trajectory_path: paths/path1.yaml
    forward_distance: 0.2
    target_speed: 0.3
    stop_distance: 0.2
    stop_ramp_coefficient: 0.5
  controller: 
    type: PID
  physics: 
    type: Internal
    model: 
      type: Unicycle
      wheel_distance: 0.25
    initial_state:
      random:
        - type: Uniform
          min:
          - -5.0
          - -5.0
          - -3.1416
          max:
          - 5.0
          - 5.0
          - 3.1416
      variable_order: [x, y, orientation]
    faults: []
  state_estimator: 
    type: Perfect
    prediction_period: 0.1
    targets:
    - self
    map_path: null
  sensor_manager:
    sensors:
    - name: RobotSensor
      send_to:
      - Central Unit
      config: 
        type: RobotSensor
        detection_distance: 100.0
        period: 0.1
        faults: []
        filters:
          - type: RangeFilter
            variables: [x, y]
            min_range: [0, -1]
            max_range: [10, 1]
  network:
    range: 0.0
    reception_delay: 0.0
  state_estimator_bench: []
- name: drone1
  navigator: 
    type: TrajectoryFollower
    trajectory_path: paths/path1.yaml
    forward_distance: 0.2
    target_speed: 1.
    stop_distance: 0.2
    stop_ramp_coefficient: 0.5
  controller: 
    type: PID
  physics: 
    type: Internal
    model: 
      type: Holonomic
computation_units:
- name: Central Unit
  network:
    range: 0.0
    reception_delay: 0.0
  state_estimators:
  - name: central_perfect
    config: 
      type: Perfect
      prediction_period: 0.1
      targets:
      - robot1
      - robot2
      map_path: null