log:
  log_level:
    Off
max_time: 60.
robots:
  - name: "robot1"
    navigator:
      External:
        config:
          None
    controller:
      External:
        config:
          None
    state_estimator:
      External:
        config:
          None
    physics:
      External:
        config:
          None