# yaml-language-server: $schema=../config.schema.json
log:
  log_level:
    Info
results:
  result_path: "../result.json"
  show_figures: false # Disabled for automatic testing
  analyse_script: "../python_scripts/analyse_results.py"
  figures_path: "../figures"
max_time: 60.
robots:
  - name: "robot1"
    navigator: 
      External: {}
    controller: 
      External: {}
    state_estimator: 
      External: {}
    physics: 
      External: {}