# yaml-language-server: $schema=../../../config.schema.json
log:
  log_level: {type: Debug}
    # type: Internal
    # value: [type: All]
results:
  result_path: "../result.json"
  show_figures: false # Disabled for automatic testing
  analyse_script: "../../../python_scripts/analyse_results.py"
  figures_path: "../figures"
time_analysis:
  exporter:
    type: TraceEventExporter
  output_path: "time_performance"
  keep_last: true
max_time: 60.
environment:
  map_path: "maps/landmarks_square.yaml"
robots:
  - name: "robot1"
    navigator: 
      type: TrajectoryFollower
      trajectory_path: "paths/path1.yaml"
      target_speed: 0.5
      forward_distance: 0.2
    controller: 
      type: PID
      proportional_gains: [1.0, 6.0]
    state_estimator: 
      type: Perfect
      prediction_activation:
        period: {type: Num, value: 0.1}
    state_estimator_bench:
      - name: "Filter"
        config: 
          type: External
          config:
            period: 0.2
    sensor_manager:
      sensors:
        - name: "LandmarkSensor"
          config: 
            type: OrientedLandmarkSensor
            detection_distance: 6.0
  - name: "robot2"
    navigator: 
      type: TrajectoryFollower
      trajectory_path: "paths/path1.yaml"
      target_speed: 0.5
      forward_distance: 0.2
    controller: 
      type: PID
      proportional_gains: [1.0, 6.0]
    state_estimator: 
      type: Perfect
      prediction_activation:
        period: {type: Num, value: 0.1}
    state_estimator_bench:
      - name: "Filter"
        config: 
          type: External
          config:
            period: 0.2
    sensor_manager:
      sensors:
        - name: "LandmarkSensor"
          config: 
            type: OrientedLandmarkSensor
            detection_distance: 6.0