# yaml-language-server: $schema=../../../config.schema.json
log:
  log_level: #!Internal ["All"]
    type: Debug
results:
  result_path: "../result.json"
  show_figures: true # Disabled for automatic testing
  analyse_script: "../../../python_scripts/analyse_results.py"
  figures_path: "../figures"
time_analysis:
  exporter:
    type: TraceEventExporter
  output_path: "time_performance"
  keep_last: true
max_time: 60.
robots:
  - name: "robot1"
    navigator: 
      type: GoTo
      target_speed: 0.5
    state_estimator: 
      type: Perfect
      prediction_period: 0.1
computation_units:
  - name: "master"
    state_estimators:
      - name: "master"
        config:
          type: External

